###consul服务端口号
server:
  port: 8004

spring:
  application:
    name: consul-provider-payment
  ####consul注册中心地址
  cloud:
    consul:
      host: 192.168.101.103
      port: 8500
      discovery:
        heartbeat:
          enabled: true
        hostname: localhost
        service-name: ${spring.application.name}

