server:
  servlet:
    context-path: /boot

spring:
  servlet:
    multipart:
      # 设置单个文件内容不超过的大小
      max-file-size: 10MB
      # 设置整个请求发送的内容不超过100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://localhost:3306/mybatistest
    password: 252525
    username: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启日志配置
    map-underscore-to-camel-case: true # 开启驼峰命名映射
