spring:
  datasource:
    username: root
    password: 252525
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus

# 注入全局MP策略配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto # 配置全局的主键策略
      table-prefix: # 配置全局的表映射前缀
  # 开启mybatis的日志配置功能
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:myMapper/*.xml